apiVersion: kost.kost.dev/v1alpha1
kind: KostConfig
metadata:
  labels:
    app.kubernetes.io/name: kost
    app.kubernetes.io/managed-by: kustomize
  name: kostconfig-sample
spec:
  pollingInterval: "5m"
  sigmaThreshold: 2.0
  minSamples: 10
  explainer:
    provider: "noop"
  pricing:
    cpuPerCoreHour: 0.034
    memoryPerGBHour: 0.0043
    gpuPerHour: 0.526
